version: '3'
services:
  mongo:
    image: mongo:7
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017

  backend:
    image: backend-service
    restart: always
    ports:
      - 3001:3001
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 3001
      DB_MONGO_DATABASE: umpisa
      DB_MONGO_USERNAME: root
      DB_MONGO_PASSWORD: password
      DB_MONGO_URL: mongodb://root:password@mongo:27017
